language: objective-c
osx_image: xcode8.2
script:
- set -o pipefail
- travis_retry xcodebuild -workspace "JSON to Swift Converter.xcodeproj" -scheme "Convert JSON to Swift"  build-for-testing test | xcpretty
